### ISSUE TITLE
Bug with last merge

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2modelfitting#27]
I got this:
```
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/m7/w45_jgp92nv46f4mjs9g8_d00000gn/T/brian_debug_zhp0bptb.log  Additionally, you can also include a copy of the script that was run, available at: /var/folders/m7/w45_jgp92nv46f4mjs9g8_d00000gn/T/brian_script_wbk4k1u0.py Thanks! [brian2]
Traceback (most recent call last):
  File "/Users/romainbrette/PycharmProjects/Paramecium-model-fitting/scripts/run_fit.py", line 202, in <module>
    callback='text', **model.bounds)
  File "/Users/romainbrette/PycharmProjects/brian2modelfitting/brian2modelfitting/fitter.py", line 495, in fit
    callback, restart, **params)
  File "/Users/romainbrette/PycharmProjects/brian2modelfitting/brian2modelfitting/fitter.py", line 302, in fit
    **params)
  File "/Users/romainbrette/PycharmProjects/brian2modelfitting/brian2modelfitting/optimizer.py", line 163, in initialize
    [bounds[i][1]])
  File "/anaconda3/envs/Paramecium-model-fitting/lib/python3.7/site-packages/nevergrad/instrumentation/variables.py", line 315, in bounded
    return self.with_transform(Transf(a_min=a_min, a_max=a_max))
  File "/anaconda3/envs/Paramecium-model-fitting/lib/python3.7/site-packages/nevergrad/instrumentation/transforms.py", line 183, in __init__
    self._b = .5 * (self.a_max + self.a_min)
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by mstimberg** [comment]
It's not related to the code in the PR, but rather to a change I made directly to master earlier (to get things working with nevergrad 0.3). I just made another commit to master, can you check whether it fixes the error for you?

**Comment by romainbrette** [comment]
It works!
